kind: pipeline
type: docker
name: aes-gtest

volumes:
- name: aes-php
  temp: {}

steps:
- name: git clone
  image: ubuntu:latest
  volumes:
  - name: aes-php
    path: /aes-php
  commands:
    - apt update
    - apt -y install git
    - cd /
    - git clone https://github.com/MinFengLin/aes-php.git aes
    - cp -r /aes/* /aes-php/

- name: aes-gtest
  image: ubuntu:latest
  volumes:
  - name: aes-php
    path: /aes-php
  commands:
    - TEST_SERVER_IP=$(cat /aes-php/test_server_ip.txt)
    - export TEST_SERVER_IP
    - echo $TEST_SERVER_IP
    - TEST_SERVER_PORT=$(cat /aes-php/test_server_port.txt)
    - export TEST_SERVER_PORT
    - echo $TEST_SERVER_PORT
    - apt update
    - apt -y install libgtest-dev cmake g++ libcurl4-openssl-dev
    - cmake --version
    - cd /usr/src/gtest
    - mkdir build 
    - cmake .. && make
    - cd lib/
    - cp -r libgtest* /usr/local/lib/
    - cd /aes-php/gtest/
    - g++ -o test aes_php-gtest.cpp -lgtest -lpthread -lcurl
    - ./test

- name: notify_telegram
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: telegram_token
    to:
      from_secret: telegram_chatid
    message: >
      {{#success build.status}}
      ✔ golint check PASS #{{build.number}} of `{{repo.name}}`.
      📝 Commit by {{commit.author}} on `{{commit.branch}}`:
      ```
      {{commit.message}}
      ```
      🔗 {{ build.link }}
      {{else}}
      ❌ golint check FAIL #{{build.number}} of `{{repo.name}}`.
      📝 Commit by {{commit.author}} on `{{commit.branch}}`:
      ```
      {{commit.message}}
      ```
      🔗 {{ build.link }}
      {{/success}}
  when:
    status: [ success, failure ]

services:
  - name: php-nginx
    image: trafex/php-nginx
    volumes:
      - name: aes-php
        path: /var/www/html
    commands:
      - export TEST_SERVER_IP=$(hostname -i)
      - echo $TEST_SERVER_IP > /var/www/html/test_server_ip.txt
      - echo $TEST_SERVER_IP
      - export TEST_SERVER_PORT=$(cat /etc/nginx/conf.d/default.conf | grep -E 'listen [0-9]+' | awk '{print $2}' | sed 's/;//' | uniq)
      - echo $TEST_SERVER_PORT > /var/www/html/test_server_port.txt
      - echo $TEST_SERVER_PORT
      - /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf

node:
  github-runner: 1
